// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using SimpleJSON;
using UnityEngine;

namespace RippleGen.Utils
{
    public static class LocalizeTools
    {
        public static Dictionary<string, string> ParserLocalize(JSONNode node) {
            Dictionary<string, string> hash = new Dictionary<string, string>();
            foreach(string key in node.Keys){
                if (hash.ContainsKey(key)) {
                    hash[key] = node[key];
                }else {
                    hash.Add(key, node[key]);
                }
            }
            return hash;
        }
    }
}

