// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace RippleGen.Utils
{
    public class Single<T> : RippleGen.Core.GenObject where T : new()
    {
        private static T instance;
        public static T Instance{
            get {
                if (instance == null) {
                    instance = new T();
                }
                return instance;
            }
        }
    }
}

