// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;

namespace RippleGen.Utils
{
    public class Wait
    {
        public static IEnumerator Do(float sec , Action action) {
            yield return new WaitForSeconds(sec);
            action();
        } 
    }
}

