// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using RippleGen.Utils;
using UnityEngine;

namespace RippleGen.Plugins
{

    public class StatusMachine<T> : RippleGen.Core.Plugin where T : struct
    {
        public delegate float StatusAction(T from, T to);

        public StatusAction OnBeforeChange;
        public StatusAction OnChange;
        public StatusAction OnAfterChange;

        bool action = false;
        public bool Ready {
            get {
                return !action;
            }
        }
        private T status;
        public T Status{
            get {
                return status;
            }
            set {
                if (!status.Equals(value) && !action) {
                    T before = status;
                    action = true;
                    doChange(OnBeforeChange, status, value, ()=> {
                        status = value;
                        doChange(OnChange, before, value, ()=> {
                            doChange(OnAfterChange, before, value, ()=>{
                                action = false;
                            });
                        });
                    });
                }
            }
        }

        public StatusMachine(T start)
        {
            status = start;
        }

        void doChange(StatusAction action, T from, T to, Action doAfter) {
            float delay = action(from, to);
            if (delay > 0) {
                Target.StartCoroutine(Wait.Do(delay, doAfter));
            }else {
                doAfter();
            }
        }
    }
}

