// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Reflection;


namespace RippleGen.Extends
{
    public static class TypeExtend
    {
        public static bool In(this Type type, Type other) {
            return type == other || type.IsSubclassOf(other);
        }

        public static object InvokeStatic(this Type type, string name, params object[] pms) {
            return type.InvokeMember(name, 
                                     BindingFlags.InvokeMethod | 
                                     BindingFlags.Public | 
                                     BindingFlags.Static, 
                                     null, null, pms);
        }
    }
}

